version: "3.8"

services:
  mediamtx:
    image: bluenviron/mediamtx
    environment:
      - MTX_RTSPTRANSPORTS=tcp
      - MTX_WEBRTCADDITIONALHOSTS=192.168.x.x
    ports:
      - "8554:8554"
      - "1935:1935"
      - "8888:8888"
      - "8889:8889"
      - "8890:8890/udp"
      - "8189:8189/udp"
      - "8554:8554/udp"
    volumes:
      - ./mediamtx.yml:/mediamtx.yml:ro
    tty: true
    stdin_open: true
